version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
    env_file:
      - .env
    restart: unless-stopped